// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates():Promise<void>;

export function GetSettings():Promise<string>;

export function GetVersion():Promise<string>;

export function LoadSettings():Promise<void>;

export function SaveSettings():Promise<void>;

export function SetSettings(arg1:string):Promise<string>;

export function ToggleFullscreen():Promise<void>;
