// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings():Promise<string>;

export function SetSettings(arg1:string,arg2:any):Promise<string>;
