name: Wails

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Package
      uses: ConorMacBride/install-package@v1.1.0
      with:
        apt: 'libwebkit2gtk-4.1-dev'

    - name: Wails Build
      uses: dAppServer/wails-build-action@v3
      with:
        build: true
        node-version: '^22.14'
        build-platform: 'linux/arm64'
        build-name: 'clock-dashboard'
        build-tags: 'webkit2_41'
